"use client";
import { useParams } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AdminFrame } from "@/features/admin/AdminFrame";
import { api,errorMessage } from "@/lib/api";
type Summary={totalPlays?:number;issuedCoupons?:number;redeemedCoupons?:number;redemptionRate?:number;todayPlays?:number};
type StoreDetail={id:number;name:string;phone:string;address:string;naverPlaceUrl:string};
export default function Dashboard(){const id=String(useParams().storeId),qc=useQueryClient(),[name,setName]=useState(""),[url,setUrl]=useState("");const q=useQuery({queryKey:["analytics",id],queryFn:()=>api<Summary>(`/admin/stores/${id}/analytics/summary`)}),store=useQuery({queryKey:["store",id],queryFn:()=>api<StoreDetail>(`/admin/stores/${id}`)});useEffect(()=>{if(store.data){setName(store.data.name);setUrl(store.data.naverPlaceUrl)}},[store.data]);const save=useMutation({mutationFn:()=>api<StoreDetail>(`/admin/stores/${id}`,{method:"PUT",body:JSON.stringify({name,naverPlaceUrl:url})}),onSuccess:()=>qc.invalidateQueries({queryKey:["store",id]})});return <AdminFrame title="대시보드">{q.isError&&<p className="error">{errorMessage(q.error)}</p>}<dl className="stats">{[["오늘 참여",q.data?.todayPlays],["전체 참여",q.data?.totalPlays],["발급 쿠폰",q.data?.issuedCoupons],["사용 쿠폰",q.data?.redeemedCoupons]].map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{value??"-"}</dd></div>)}</dl><form className="panel stack" onSubmit={(e:FormEvent)=>{e.preventDefault();save.mutate()}}><h2>매장 기본 정보</h2><div className="field"><label htmlFor="store-name">매장명</label><input id="store-name" value={name} onChange={e=>setName(e.target.value)} required/></div><div className="field"><label htmlFor="naver-url">네이버 플레이스 URL</label><input id="naver-url" type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://map.naver.com/..."/></div>{save.isError&&<p className="error">{errorMessage(save.error)}</p>}<button className="btn" disabled={save.isPending}>저장</button></form></AdminFrame>}
