"use client";
import { FormEvent, useState } from "react";
import { useParams } from "next/navigation";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { AdminFrame } from "@/features/admin/AdminFrame";
import { api,errorMessage } from "@/lib/api";
import type { Prize } from "@/types/api";
import { TIER_LABEL,TIER_ODDS,TIER_YUT } from "@/features/labels";
function PrizeCard({storeId,prize}:{storeId:string;prize:Prize}){const qc=useQueryClient(),[form,setForm]=useState(prize);const m=useMutation({mutationFn:()=>api<Prize>(`/admin/stores/${storeId}/prizes/${prize.tier}`,{method:"PUT",body:JSON.stringify({name:form.name,description:form.description,redeemPolicy:form.redeemPolicy,active:form.active})}),onSuccess:()=>qc.invalidateQueries({queryKey:["prizes",storeId]})});return <form className="card" onSubmit={(e:FormEvent)=>{e.preventDefault();m.mutate()}}><div className="row"><h2>{TIER_LABEL[prize.tier]} 상품</h2><span className="pill">{TIER_YUT[prize.tier]} · 확률 {TIER_ODDS[prize.tier]} 고정</span></div><div className="field"><label>상품명</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>설명</label><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="field"><label>사용 시점</label><select value={form.redeemPolicy} onChange={e=>setForm({...form,redeemPolicy:e.target.value as Prize["redeemPolicy"]})}><option value="ANYTIME">즉시</option><option value="SAME_DAY">당일</option><option value="NEXT_DAY">다음 날</option></select></div><label className="check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>상품 활성화</label>{m.isError&&<p className="error">{errorMessage(m.error)}</p>}<button className="btn" disabled={m.isPending}>저장</button></form>}
export default function Prizes(){const id=String(useParams().storeId),q=useQuery({queryKey:["prizes",id],queryFn:()=>api<Prize[]>(`/admin/stores/${id}/prizes`)});return <AdminFrame title="상품 설정"><p className="lead">당첨 확률은 시스템에서 고정하며 변경할 수 없습니다.</p>{q.isError&&<p className="error">{errorMessage(q.error)}</p>}<div className="grid">{q.data?.map(p=><PrizeCard key={p.tier} storeId={id} prize={p}/>)}</div></AdminFrame>}

