package com.yutreview;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import jakarta.servlet.http.HttpServletRequest;
import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.time.Clock;
import java.util.*;
import org.springframework.data.domain.*;
import org.springframework.http.*;
import org.springframework.security.core.Authentication;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.bind.annotation.*;
import org.springframework.transaction.annotation.Transactional;

@RestController @RequestMapping("/api/admin") class AdminController {
    /** 한 계정이 여러 매장을 관리할 수 있다. 상한은 실수와 자동 생성으로부터 지키는 선이지 정책이 아니다. */
    private static final int MAX_STORES_PER_ADMIN=20;
    private final AdminUserRepository admins;private final MembershipRepository memberships;private final StoreRepository stores;private final StoreAccessService access;private final PrizeRepository prizes;private final GameConfigService gameConfig;private final StoreEventSettingsService eventSettings;private final QrRepository qrs;private final StorePosterRepository posterRepository;private final StorePosterService posters;private final GameRepository games;private final CouponRepository coupons;private final AnalyticsService analytics;private final SubscriptionService subscriptions;private final PlanEntitlementService entitlements;private final PasswordEncoder encoder;private final JwtService jwt;private final SecureRandom random;private final Clock clock;private final PhoneService personalData;private final LoginAttemptLimiter loginLimiter;private final StoreProvisioningService provisioning;private final AdminSignupService signup;private final PublicOriginResolver publicOrigins;private final MarketingConsentService marketingConsents;private final StoreApprovalService approvals;private final ClientIpResolver clientIps;
    AdminController(AdminUserRepository admins,MembershipRepository memberships,StoreRepository stores,StoreAccessService access,PrizeRepository prizes,GameConfigService gameConfig,StoreEventSettingsService eventSettings,QrRepository qrs,StorePosterRepository posterRepository,StorePosterService posters,GameRepository games,CouponRepository coupons,AnalyticsService analytics,SubscriptionService subscriptions,PlanEntitlementService entitlements,PasswordEncoder encoder,JwtService jwt,SecureRandom random,Clock clock,PhoneService personalData,LoginAttemptLimiter loginLimiter,StoreProvisioningService provisioning,AdminSignupService signup,PublicOriginResolver publicOrigins,MarketingConsentService marketingConsents,StoreApprovalService approvals,ClientIpResolver clientIps){this.admins=admins;this.memberships=memberships;this.stores=stores;this.access=access;this.prizes=prizes;this.gameConfig=gameConfig;this.eventSettings=eventSettings;this.qrs=qrs;this.posterRepository=posterRepository;this.posters=posters;this.games=games;this.coupons=coupons;this.analytics=analytics;this.subscriptions=subscriptions;this.entitlements=entitlements;this.encoder=encoder;this.jwt=jwt;this.random=random;this.clock=clock;this.personalData=personalData;this.loginLimiter=loginLimiter;this.provisioning=provisioning;this.signup=signup;this.publicOrigins=publicOrigins;this.marketingConsents=marketingConsents;this.approvals=approvals;this.clientIps=clientIps;}
    record Login(@NotBlank @Size(max=255) String email,@NotBlank @Size(max=128) String password){}
    record SignUp(@NotBlank @Size(max=128) String password,@NotBlank @Size(max=128) String passwordConfirm,@NotBlank @Size(max=255) String email,@NotBlank @Size(max=50) String ownerName,@NotBlank @Size(max=20) String phone,@NotBlank @Size(max=100) String storeName,@NotBlank @Size(max=20) String businessNumber,boolean termsAgreed,@Size(max=20) String termsVersion,boolean privacyAgreed,@Size(max=20) String privacyVersion,@Size(max=20) String marketingVersion,boolean yutReviewMarketing,boolean reviewPilotMarketing,boolean sodamMarketing){} record StoreCreate(@NotBlank @Size(max=100) String name,@NotBlank @Size(max=20) String businessNumber,@NotBlank @Size(max=20) String phone,@Size(max=255) String address,@Size(max=500) @Pattern(regexp="|https?://.*") String naverPlaceUrl){} record StoreUpdate(@NotBlank @Size(max=100) String name,@Size(max=30) String phone,@Size(max=255) String address,@Size(max=500) @Pattern(regexp="|https?://.*") String naverPlaceUrl,@Size(max=60) String posterTagline){} record PrizeUpdate(@NotBlank @Size(max=100) String name,@Size(max=500) String description,@NotNull RedeemPolicy redeemPolicy,boolean active){}
    record MarketingConsentUpdate(@NotNull MarketingService service,boolean agreed,@NotBlank @Size(max=20) String version){}
    record EventSettingsUpdate(Integer couponValidityDays){}
    record OutcomeSetting(@NotNull YutResult yutResult,int weight,int prizeRank){} record GameConfigUpdate(@NotNull List<@NotNull @Valid OutcomeSetting> outcomes){}
    record EventPrizeSetting(@Min(1) @Max(StoreOutcome.MAX_RANK) int rank,@NotBlank @Size(max=100) String name,@Size(max=500) String description,@NotNull RedeemPolicy redeemPolicy){}
    record EventConfigurationUpdate(@NotNull @Size(min=5,max=5) List<@NotNull @Valid OutcomeSetting> outcomes,@NotNull @Size(min=1,max=StoreOutcome.MAX_RANK) List<@NotNull @Valid EventPrizeSetting> prizes){}
    private Map<String,Object> eventSettingsView(Long storeId){return Map.of("couponValidityDays",eventSettings.couponValidityDays(storeId),"minDays",StoreEventSettings.MIN_COUPON_VALIDITY_DAYS,"maxDays",StoreEventSettings.MAX_COUPON_VALIDITY_DAYS,"defaultDays",StoreEventSettings.DEFAULT_COUPON_VALIDITY_DAYS);}
    record PageView<T>(List<T> content,int page,int size,long totalElements,int totalPages){}
    /**
     * 셀프 가입. 계정과 매장은 만들어지지만 매장은 PENDING_APPROVAL이다.
     *
     * 직원 PIN과 QR 토큰을 여기서 돌려주지 않는다. 승인 전에는 쓸 수 없는 값이고, 승인 뒤에는
     * 매장 화면에서 다시 받을 수 있다. 받자마자 못 쓰는 비밀을 화면에 띄우는 것이 더 나쁘다.
     */
    @PostMapping("/auth/signup") ApiResponse<?> signUp(@Valid @RequestBody SignUp r,HttpServletRequest req){StoreProvisioningService.Provisioned p=signup.signUp(new AdminSignupService.Request(r.password,r.passwordConfirm,r.email,r.ownerName,r.phone,r.storeName,r.businessNumber,r.termsAgreed,r.termsVersion,r.privacyAgreed,r.privacyVersion,r.marketingVersion,r.yutReviewMarketing,r.reviewPilotMarketing,r.sodamMarketing),origin(req),clientIps.resolve(req));return ApiResponse.ok(Map.of("storeId",p.store().id,"storeName",p.store().name,"status",p.store().status.name(),"approvalRequired",p.store().status!=StoreStatus.ACTIVE));}
    @PostMapping("/auth/login") ApiResponse<?> login(@Valid @RequestBody Login r,HttpServletRequest req){String ip=clientIps.resolve(req),email=Inputs.lower(r.email);loginLimiter.attempt(ip,email);AdminUser u=admins.findByEmail(email).filter(a->encoder.matches(r.password,a.passwordHash)).orElseThrow(()->new AppException("AUTH_INVALID","이메일 또는 비밀번호가 올바르지 않습니다.",org.springframework.http.HttpStatus.UNAUTHORIZED));loginLimiter.succeeded(ip,email);return ApiResponse.ok(Map.of("accessToken",jwt.issue(u),"tokenType","Bearer"));}
    @GetMapping("/stores") ApiResponse<?> stores(Authentication a){return ApiResponse.ok(memberships.findByAdminId(adminId(a)).stream().map(m->Map.of("id",m.store.id,"name",m.store.name,"businessNumber",m.store.businessNumber==null?"":m.store.businessNumber,"status",m.store.status,"approvalNote",m.store.status==StoreStatus.REJECTED?approvals.rejectionNote(m.store.id):"")).toList());}
    /** 화면이 운영자 메뉴를 보여 줄지 판단할 근거. 역할 판단을 클라이언트가 추측하지 않게 한다. */
    @GetMapping("/me") ApiResponse<?> me(Authentication a){AdminUser u=admins.findById(adminId(a)).orElseThrow(()->new AppException("AUTH_REQUIRED","로그인이 필요합니다.",org.springframework.http.HttpStatus.UNAUTHORIZED));return ApiResponse.ok(Map.of("id",u.id,"email",u.email,"name",u.name,"role",u.role.name()));}
    @GetMapping("/marketing-consents") ApiResponse<?> marketingConsentList(Authentication a){return ApiResponse.ok(marketingConsents.current(adminId(a)));}
    @PutMapping("/marketing-consents") ApiResponse<?> updateMarketingConsent(@Valid @RequestBody MarketingConsentUpdate r,Authentication a){AdminUser admin=admins.findById(adminId(a)).orElseThrow();return ApiResponse.ok(marketingConsents.update(admin,r.service,r.agreed,r.version));}
    @PostMapping("/stores") @Transactional ApiResponse<?> createStore(@Valid @RequestBody StoreCreate r,Authentication auth,HttpServletRequest req){AdminUser admin=admins.findById(adminId(auth)).orElseThrow();String name=Inputs.required(r.name,"매장 상호명을 입력해 주세요."),phone=Inputs.phone(r.phone),business=Inputs.businessNumber(r.businessNumber);if(memberships.countByAdminId(admin.id)>=MAX_STORES_PER_ADMIN)throw new AppException("STORE_LIMIT_REACHED","한 계정이 관리할 수 있는 매장 수를 넘었습니다.");if(stores.existsByBusinessNumber(business))throw new AppException("DUPLICATE_BUSINESS_NUMBER","이미 등록된 사업자등록번호입니다.");StoreProvisioningService.Provisioned p=provisioning.provision(admin,name,phone,r.address,business,r.naverPlaceUrl,null,origin(req));return ApiResponse.ok(Map.of("id",p.store().id,"name",p.store().name,"status",p.store().status.name(),"approvalRequired",p.store().status!=StoreStatus.ACTIVE));}
    @GetMapping("/stores/{id}") ApiResponse<?> store(@PathVariable Long id,Authentication a){member(a,id);return ApiResponse.ok(storeView(store(id)));}
    @PutMapping("/stores/{id}") @Transactional ApiResponse<?> updateStore(@PathVariable Long id,@Valid @RequestBody StoreUpdate r,Authentication a,HttpServletRequest req){operable(a,id);Store s=store(id);s.name=r.name.trim();if(r.phone!=null)s.phone=r.phone.trim();if(r.address!=null)s.address=r.address;if(r.naverPlaceUrl!=null)s.naverPlaceUrl=r.naverPlaceUrl;
        // 안내물 문구는 브랜딩 권한이 있는 요금제에서만 바꿀 수 있다. 없는 등급이 보내면 무시가 아니라 거부다.
        if(r.posterTagline!=null&&!r.posterTagline.equals(s.posterTagline==null?"":s.posterTagline)){entitlements.require(subscriptions.planOf(id),Entitlement.BRANDING);s.posterTagline=r.posterTagline.isBlank()?null:r.posterTagline.trim();}
        s.updatedAt=clock.instant();qrs.findFirstByStoreIdAndStatus(id,QrStatus.ACTIVE).ifPresent(q->posters.save(s,q.publicToken,origin(req),s.posterTagline));return ApiResponse.ok(storeView(s));}
    @GetMapping("/stores/{id}/prizes") ApiResponse<?> prizes(@PathVariable Long id,Authentication a){operable(a,id);return ApiResponse.ok(prizes.findByStoreIdOrderByRank(id).stream().map(this::prizeView).toList());}
    @PutMapping("/stores/{id}/prizes/{rank}") @Transactional ApiResponse<?> prize(@PathVariable Long id,@PathVariable int rank,@Valid @RequestBody PrizeUpdate r,Authentication a){operable(a,id);Prize p=prizes.findByStoreIdAndRank(id,rank).orElseThrow(()->new AppException("PRIZE_NOT_FOUND","상품을 찾을 수 없습니다."));p.name=r.name;p.description=r.description;p.redeemPolicy=r.redeemPolicy;p.active=r.active;p.updatedAt=clock.instant();return ApiResponse.ok(prizeView(p));}
    @GetMapping("/stores/{id}/game-config") ApiResponse<?> gameConfig(@PathVariable Long id,Authentication a){operable(a,id);return ApiResponse.ok(gameConfigView(gameConfig.load(id)));}
    @PutMapping("/stores/{id}/game-config") ApiResponse<?> saveGameConfig(@PathVariable Long id,@Valid @RequestBody GameConfigUpdate r,Authentication a){operable(a,id);List<GameConfigService.Setting> settings=r.outcomes()==null?List.of():r.outcomes().stream().map(o->new GameConfigService.Setting(o.yutResult(),o.weight(),o.prizeRank())).toList();return ApiResponse.ok(gameConfigView(gameConfig.save(store(id),settings)));}
    @PutMapping("/stores/{id}/event-configuration") ApiResponse<?> saveEventConfiguration(@PathVariable Long id,@Valid @RequestBody EventConfigurationUpdate r,Authentication a){operable(a,id);GameConfigService.EventConfiguration saved=gameConfig.saveEventConfiguration(store(id),r.outcomes().stream().map(o->new GameConfigService.Setting(o.yutResult(),o.weight(),o.prizeRank())).toList(),r.prizes().stream().map(p->new GameConfigService.PrizeSetting(p.rank(),p.name(),p.description(),p.redeemPolicy())).toList());return ApiResponse.ok(eventConfigurationView(saved));}
    /**
     * 쿠폰 사용 기한. 저장한 값은 이 시점 이후 새로 발급되는 쿠폰에만 적용되고,
     * 이미 발급된 쿠폰의 만료일은 건드리지 않는다.
     */
    @GetMapping("/stores/{id}/event-settings") ApiResponse<?> eventSettings(@PathVariable Long id,Authentication a){operable(a,id);return ApiResponse.ok(eventSettingsView(id));}
    @PutMapping("/stores/{id}/event-settings") ApiResponse<?> saveEventSettings(@PathVariable Long id,@RequestBody EventSettingsUpdate r,Authentication a){operable(a,id);eventSettings.save(store(id),r.couponValidityDays());return ApiResponse.ok(eventSettingsView(id));}
    @GetMapping("/stores/{id}/qr-codes") ApiResponse<?> qrs(@PathVariable Long id,Authentication a){operable(a,id);return ApiResponse.ok(qrs.findByStoreIdOrderByCreatedAtDesc(id).stream().map(q->Map.of("token",q.publicToken,"status",q.status,"createdAt",q.createdAt)).toList());}
    @PostMapping("/stores/{id}/qr-codes/regenerate") @Transactional ApiResponse<?> regenerateQr(@PathVariable Long id,Authentication a,HttpServletRequest req){operable(a,id);Store s=stores.findForUpdate(id).orElseThrow(()->new AppException("STORE_NOT_FOUND","매장을 찾을 수 없습니다."));qrs.findFirstByStoreIdAndStatus(id,QrStatus.ACTIVE).ifPresent(q->{q.status=QrStatus.REVOKED;q.revokedAt=clock.instant();});StoreQrCode q=new StoreQrCode();q.store=s;q.publicToken=Tokens.random();q.status=QrStatus.ACTIVE;q.createdAt=clock.instant();qrs.save(q);posters.save(s,q.publicToken,origin(req));return ApiResponse.ok(Map.of("token",q.publicToken,"posterReady",true));}
    @GetMapping(value="/stores/{id}/poster",produces=MediaType.IMAGE_PNG_VALUE) @Transactional ResponseEntity<byte[]> poster(@PathVariable Long id,Authentication a,HttpServletRequest req){operable(a,id);Store s=store(id);StorePoster poster=posterRepository.findByStoreId(id).orElseGet(()->{StoreQrCode q=qrs.findFirstByStoreIdAndStatus(id,QrStatus.ACTIVE).orElseThrow(()->new AppException("QR_TOKEN_INVALID","활성 QR이 없습니다."));return posters.save(s,q.publicToken,origin(req));});String filename=s.name.replaceAll("[\\r\\n\\\\/:*?\"<>|]","_")+"_A6_QR.png";return ResponseEntity.ok().cacheControl(CacheControl.noStore()).header("X-Poster-Public-Origin",poster.publicOrigin).header(HttpHeaders.CONTENT_DISPOSITION,ContentDisposition.attachment().filename(filename,StandardCharsets.UTF_8).build().toString()).body(posters.bytes(poster));}
    @PostMapping("/stores/{id}/poster/regenerate") @Transactional ApiResponse<?> regeneratePoster(@PathVariable Long id,Authentication a,HttpServletRequest req){operable(a,id);Store s=store(id);StoreQrCode q=qrs.findFirstByStoreIdAndStatus(id,QrStatus.ACTIVE).orElseThrow(()->new AppException("QR_TOKEN_INVALID","활성 QR이 없습니다."));StorePoster poster=posters.save(s,q.publicToken,origin(req),s.posterTagline);return ApiResponse.ok(Map.of("updatedAt",poster.updatedAt,"publicOrigin",poster.publicOrigin));}
    @PostMapping("/stores/{id}/staff-pin/regenerate") @Transactional ApiResponse<?> regeneratePin(@PathVariable Long id,Authentication a){operable(a,id);String pin=Integer.toString(100000+random.nextInt(900000));Store s=store(id);s.staffPinHash=encoder.encode(pin);s.updatedAt=clock.instant();return ApiResponse.ok(Map.of("pin",pin));}
    @GetMapping("/stores/{id}/game-plays") ApiResponse<?> games(@PathVariable Long id,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="50") int size,Authentication a){operable(a,id);PageRequest request=pageRequest(page,size);return ApiResponse.ok(pageView(games.findByStoreIdOrderByPlayedAtDesc(id,request).map(g->Map.of("playId",g.publicId,"customerName",personalData.decrypt(g.customerNameEncrypted),"phoneLast4",g.phoneLast4,"result",g.yutResult,"prizeRank",g.prizeRank,"status",g.status,"playedAt",g.playedAt))));}
    @GetMapping("/stores/{id}/coupons") ApiResponse<?> coupons(@PathVariable Long id,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="50") int size,Authentication a){operable(a,id);PageRequest request=pageRequest(page,size);return ApiResponse.ok(pageView(coupons.findByStoreIdOrderByIssuedAtDesc(id,request).map(c->Map.of("token",c.couponToken,"customerName",personalData.decrypt(c.gamePlay.customerNameEncrypted),"phoneLast4",c.gamePlay.phoneLast4,"prizeName",c.prizeNameSnapshot,"status",c.status,"issuedAt",c.issuedAt,"expiresAt",c.expiresAt))));}
    @GetMapping("/stores/{id}/analytics/summary") ApiResponse<?> analytics(@PathVariable Long id,Authentication a){operable(a,id);return ApiResponse.ok(analytics.summary(id));}
    /** STANDARD 이상. 시간대·요일·상품별·재참여. 요금제에 없으면 402로 막힌다. */
    @GetMapping("/stores/{id}/analytics/detailed") ApiResponse<?> detailedAnalytics(@PathVariable Long id,@RequestParam(required=false) @org.springframework.format.annotation.DateTimeFormat(iso=org.springframework.format.annotation.DateTimeFormat.ISO.DATE) java.time.LocalDate from,@RequestParam(required=false) @org.springframework.format.annotation.DateTimeFormat(iso=org.springframework.format.annotation.DateTimeFormat.ISO.DATE) java.time.LocalDate to,Authentication a){operable(a,id);return ApiResponse.ok(analytics.detailed(id,from,to));}
    /** STANDARD 이상. 집계만 담은 CSV로, 고객 개인정보는 한 칸도 들어가지 않는다. */
    @GetMapping(value="/stores/{id}/analytics/export/{kind}",produces="text/csv; charset=UTF-8") ResponseEntity<String> exportCsv(@PathVariable Long id,@PathVariable String kind,@RequestParam(required=false) @org.springframework.format.annotation.DateTimeFormat(iso=org.springframework.format.annotation.DateTimeFormat.ISO.DATE) java.time.LocalDate from,@RequestParam(required=false) @org.springframework.format.annotation.DateTimeFormat(iso=org.springframework.format.annotation.DateTimeFormat.ISO.DATE) java.time.LocalDate to,Authentication a){
        operable(a,id);Store s=store(id);
        java.time.LocalDate end=to==null?java.time.LocalDate.now(clock):to,start=from==null?end.minusDays(29):from;
        String body=switch(kind){case "daily"->analytics.dailyCsv(id,start,end);case "prize"->analytics.prizeCsv(id,start,end);default->throw new AppException("INVALID_REQUEST","내보낼 수 있는 항목은 daily, prize입니다.");};
        String filename=AnalyticsService.safeFileName(s.name,kind,start,end);
        return ResponseEntity.ok().cacheControl(CacheControl.noStore()).header(HttpHeaders.CONTENT_DISPOSITION,ContentDisposition.attachment().filename(filename,StandardCharsets.UTF_8).build().toString()).body(body);}
    private void member(Authentication a,Long id){access.member(adminId(a),id);}
    /**
     * 운영 기능은 매장이 ACTIVE일 때만 열린다.
     *
     * 사업자등록번호는 신청자가 적어 넣은 주장이라, 운영자가 확인하기 전에는 QR·PIN·포스터·분석이
     * 열리면 안 된다. 상태 확인용 조회(GET /stores/{id})만 이 문을 지나지 않는다. 자기 신청이
     * 어떻게 됐는지조차 못 보면 승인 흐름이 그냥 고장난 화면이 된다.
     */
    private void operable(Authentication a,Long id){member(a,id);approvals.requireOperable(store(id));} private Long adminId(Authentication a){return (Long)a.getPrincipal();} private Store store(Long id){return stores.findById(id).orElseThrow(()->new AppException("STORE_NOT_FOUND","매장을 찾을 수 없습니다."));}
    private Map<String,Object> gameConfigView(List<StoreOutcome> config){return Map.of("rankCount",GameConfigService.rankCount(config),"outcomes",config.stream().map(o->Map.of("yutResult",o.yutResult,"weight",o.weight,"prizeRank",o.prizeRank,"odds",GameConfigService.odds(config,x->x.yutResult==o.yutResult))).toList());}
    private Map<String,Object> eventConfigurationView(GameConfigService.EventConfiguration config){Map<String,Object> view=new LinkedHashMap<>(gameConfigView(config.outcomes()));view.put("prizes",config.prizes().stream().map(this::prizeView).toList());return view;}
    private Map<String,Object> prizeView(Prize p){return Map.of("rank",p.rank,"name",p.name,"description",p.description==null?"":p.description,"redeemPolicy",p.redeemPolicy,"active",p.active);}
    private Map<String,Object> storeView(Store s){return Map.of("id",s.id,"name",s.name,"phone",s.phone,"address",s.address==null?"":s.address,"naverPlaceUrl",s.naverPlaceUrl==null?"":s.naverPlaceUrl,"posterTagline",s.posterTagline==null?"":s.posterTagline,"brandingAvailable",entitlements.has(subscriptions.planOf(s.id),Entitlement.BRANDING),"csvExports",analytics.availableExports(s.id),"status",s.status,"approvalNote",s.status==StoreStatus.REJECTED?approvals.rejectionNote(s.id):"");}
    private PageRequest pageRequest(int page,int size){if(page<0||size<1||size>100)throw new AppException("INVALID_REQUEST","page는 0 이상, size는 1~100이어야 합니다.");return PageRequest.of(page,size);}
    private <T> PageView<T> pageView(Page<T> page){return new PageView<>(page.getContent(),page.getNumber(),page.getSize(),page.getTotalElements(),page.getTotalPages());}
    private String origin(HttpServletRequest request){return publicOrigins.resolve(request);}
}
