package com.yutreview;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import jakarta.servlet.http.HttpServletRequest;
import java.security.SecureRandom;
import java.time.Clock;
import java.util.*;
import org.springframework.security.core.Authentication;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.bind.annotation.*;
import org.springframework.transaction.annotation.Transactional;

@RestController @RequestMapping("/api/admin") class AdminController {
    private final AdminUserRepository admins;private final MembershipRepository memberships;private final StoreRepository stores;private final StoreAccessService access;private final PrizeRepository prizes;private final QrRepository qrs;private final GameRepository games;private final CouponRepository coupons;private final PasswordEncoder encoder;private final JwtService jwt;private final SecureRandom random;private final Clock clock;private final PhoneService personalData;private final LoginAttemptLimiter loginLimiter;
    AdminController(AdminUserRepository admins,MembershipRepository memberships,StoreRepository stores,StoreAccessService access,PrizeRepository prizes,QrRepository qrs,GameRepository games,CouponRepository coupons,PasswordEncoder encoder,JwtService jwt,SecureRandom random,Clock clock,PhoneService personalData,LoginAttemptLimiter loginLimiter){this.admins=admins;this.memberships=memberships;this.stores=stores;this.access=access;this.prizes=prizes;this.qrs=qrs;this.games=games;this.coupons=coupons;this.encoder=encoder;this.jwt=jwt;this.random=random;this.clock=clock;this.personalData=personalData;this.loginLimiter=loginLimiter;}
    record Login(@Email @Size(max=255) String email,@NotBlank @Size(max=128) String password){} record StoreCreate(@NotBlank @Size(max=100) String name,@Size(max=30) String phone,@Size(max=255) String address,@Size(max=500) @Pattern(regexp="|https?://.*") String naverPlaceUrl){} record StoreUpdate(@NotBlank @Size(max=100) String name,@Size(max=30) String phone,@Size(max=255) String address,@Size(max=500) @Pattern(regexp="|https?://.*") String naverPlaceUrl){} record PrizeUpdate(@NotBlank @Size(max=100) String name,@Size(max=500) String description,@NotNull RedeemPolicy redeemPolicy,boolean active){}
    @PostMapping("/auth/login") ApiResponse<?> login(@Valid @RequestBody Login r,HttpServletRequest req){String ip=clientIp(req);loginLimiter.attempt(ip);AdminUser u=admins.findByEmail(r.email.toLowerCase()).filter(a->encoder.matches(r.password,a.passwordHash)).orElseThrow(()->new AppException("AUTH_INVALID","이메일 또는 비밀번호가 올바르지 않습니다.",org.springframework.http.HttpStatus.UNAUTHORIZED));loginLimiter.succeeded(ip);return ApiResponse.ok(Map.of("accessToken",jwt.issue(u),"tokenType","Bearer"));}
    @GetMapping("/stores") ApiResponse<?> stores(Authentication a){return ApiResponse.ok(memberships.findByAdminId(adminId(a)).stream().map(m->Map.of("id",m.store.id,"name",m.store.name,"status",m.store.status)).toList());}
    @PostMapping("/stores") @Transactional ApiResponse<?> createStore(@Valid @RequestBody StoreCreate r,Authentication auth){AdminUser admin=admins.findById(adminId(auth)).orElseThrow();if(admin.role!=AdminRole.SYSTEM_ADMIN)throw new AppException("FORBIDDEN","매장 생성 권한이 없습니다.",org.springframework.http.HttpStatus.FORBIDDEN);var now=clock.instant();String pin=Integer.toString(100000+random.nextInt(900000));Store s=new Store();s.name=r.name.trim();s.phone=r.phone==null?"":r.phone.trim();s.address=r.address;s.naverPlaceUrl=r.naverPlaceUrl;s.staffPinHash=encoder.encode(pin);s.status=StoreStatus.ACTIVE;s.createdAt=now;s.updatedAt=now;stores.save(s);AdminStoreMembership m=new AdminStoreMembership();m.admin=admin;m.store=s;m.role=MembershipRole.OWNER;m.createdAt=now;memberships.save(m);StoreQrCode q=new StoreQrCode();q.store=s;q.publicToken=StaffVerificationService.randomToken();q.status=QrStatus.ACTIVE;q.createdAt=now;qrs.save(q);for(Tier tier:Tier.values()){Prize p=new Prize();p.store=s;p.tier=tier;p.name=tier.name()+" 상품";p.description="관리자에서 상품을 설정하세요.";p.redeemPolicy=RedeemPolicy.ANYTIME;p.active=true;p.createdAt=now;p.updatedAt=now;prizes.save(p);}return ApiResponse.ok(Map.of("id",s.id,"name",s.name,"staffPin",pin,"storeToken",q.publicToken));}
    @GetMapping("/stores/{id}") ApiResponse<?> store(@PathVariable Long id,Authentication a){member(a,id);return ApiResponse.ok(storeView(store(id)));}
    @PutMapping("/stores/{id}") @Transactional ApiResponse<?> updateStore(@PathVariable Long id,@Valid @RequestBody StoreUpdate r,Authentication a){member(a,id);Store s=store(id);s.name=r.name.trim();if(r.phone!=null)s.phone=r.phone.trim();if(r.address!=null)s.address=r.address;if(r.naverPlaceUrl!=null)s.naverPlaceUrl=r.naverPlaceUrl;s.updatedAt=clock.instant();return ApiResponse.ok(storeView(s));}
    @GetMapping("/stores/{id}/prizes") ApiResponse<?> prizes(@PathVariable Long id,Authentication a){member(a,id);return ApiResponse.ok(prizes.findByStoreIdOrderByTier(id).stream().map(this::prizeView).toList());}
    @PutMapping("/stores/{id}/prizes/{tier}") @Transactional ApiResponse<?> prize(@PathVariable Long id,@PathVariable Tier tier,@Valid @RequestBody PrizeUpdate r,Authentication a){member(a,id);Prize p=prizes.findByStoreIdAndTier(id,tier).orElseThrow(()->new AppException("PRIZE_NOT_FOUND","상품을 찾을 수 없습니다."));p.name=r.name;p.description=r.description;p.redeemPolicy=r.redeemPolicy;p.active=r.active;p.updatedAt=clock.instant();return ApiResponse.ok(prizeView(p));}
    @GetMapping("/stores/{id}/qr-codes") ApiResponse<?> qrs(@PathVariable Long id,Authentication a){member(a,id);return ApiResponse.ok(qrs.findByStoreIdOrderByCreatedAtDesc(id).stream().map(q->Map.of("token",q.publicToken,"status",q.status,"createdAt",q.createdAt)).toList());}
    @PostMapping("/stores/{id}/qr-codes/regenerate") @Transactional ApiResponse<?> regenerateQr(@PathVariable Long id,Authentication a){member(a,id);Store s=stores.findForUpdate(id).orElseThrow(()->new AppException("STORE_NOT_FOUND","매장을 찾을 수 없습니다."));qrs.findFirstByStoreIdAndStatus(id,QrStatus.ACTIVE).ifPresent(q->{q.status=QrStatus.REVOKED;q.revokedAt=clock.instant();});StoreQrCode q=new StoreQrCode();q.store=s;q.publicToken=StaffVerificationService.randomToken();q.status=QrStatus.ACTIVE;q.createdAt=clock.instant();qrs.save(q);return ApiResponse.ok(Map.of("token",q.publicToken));}
    @PostMapping("/stores/{id}/staff-pin/regenerate") @Transactional ApiResponse<?> regeneratePin(@PathVariable Long id,Authentication a){member(a,id);String pin=Integer.toString(100000+random.nextInt(900000));Store s=store(id);s.staffPinHash=encoder.encode(pin);s.updatedAt=clock.instant();return ApiResponse.ok(Map.of("pin",pin));}
    @GetMapping("/stores/{id}/game-plays") ApiResponse<?> games(@PathVariable Long id,Authentication a){member(a,id);return ApiResponse.ok(games.findByStoreIdOrderByPlayedAtDesc(id).stream().map(g->Map.of("playId",g.publicId,"customerName",personalData.decrypt(g.customerNameEncrypted),"phoneLast4",g.phoneLast4,"result",g.yutResult,"tier",g.rewardTier,"status",g.status,"playedAt",g.playedAt)).toList());}
    @GetMapping("/stores/{id}/coupons") ApiResponse<?> coupons(@PathVariable Long id,Authentication a){member(a,id);return ApiResponse.ok(coupons.findByStoreIdOrderByIssuedAtDesc(id).stream().map(c->Map.of("token",c.couponToken,"prizeName",c.prizeNameSnapshot,"status",c.status,"issuedAt",c.issuedAt,"expiresAt",c.expiresAt)).toList());}
    @GetMapping("/stores/{id}/analytics/summary") ApiResponse<?> analytics(@PathVariable Long id,Authentication a){member(a,id);Map<String,Long> results=new LinkedHashMap<>();for(YutResult result:YutResult.values())results.put(result.name(),games.countByStoreIdAndYutResult(id,result));return ApiResponse.ok(Map.of("todayPlays",games.countByStoreIdAndPlayedDate(id,java.time.LocalDate.now(clock)),"totalPlays",games.countByStoreId(id),"issuedCoupons",coupons.countByStoreIdAndStatus(id,CouponStatus.ISSUED),"redeemedCoupons",coupons.countByStoreIdAndStatus(id,CouponStatus.REDEEMED),"results",results));}
    private void member(Authentication a,Long id){access.member(adminId(a),id);} private Long adminId(Authentication a){return (Long)a.getPrincipal();} private Store store(Long id){return stores.findById(id).orElseThrow(()->new AppException("STORE_NOT_FOUND","매장을 찾을 수 없습니다."));}
    private Map<String,Object> prizeView(Prize p){return Map.of("tier",p.tier,"name",p.name,"description",p.description==null?"":p.description,"redeemPolicy",p.redeemPolicy,"active",p.active);}
    private Map<String,Object> storeView(Store s){return Map.of("id",s.id,"name",s.name,"phone",s.phone,"address",s.address==null?"":s.address,"naverPlaceUrl",s.naverPlaceUrl==null?"":s.naverPlaceUrl,"status",s.status);}
    private String clientIp(HttpServletRequest r){String proxied=r.getHeader("X-Real-IP");return proxied==null||proxied.isBlank()?r.getRemoteAddr():proxied;}
}
