package com.yutreview;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import jakarta.servlet.http.HttpServletRequest;
import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.time.Clock;
import java.util.*;
import org.springframework.http.*;
import org.springframework.security.core.Authentication;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.bind.annotation.*;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

@RestController @RequestMapping("/api/admin") class AdminController {
    /** 한 계정이 여러 매장을 관리할 수 있다. 상한은 실수와 자동 생성으로부터 지키는 선이지 정책이 아니다. */
    private static final int MAX_STORES_PER_ADMIN=20;
    private final AdminUserRepository admins;private final MembershipRepository memberships;private final StoreRepository stores;private final StoreAccessService access;private final PrizeRepository prizes;private final GameConfigService gameConfig;private final QrRepository qrs;private final StorePosterRepository posterRepository;private final StorePosterService posters;private final GameRepository games;private final CouponRepository coupons;private final PasswordEncoder encoder;private final JwtService jwt;private final SecureRandom random;private final Clock clock;private final PhoneService personalData;private final LoginAttemptLimiter loginLimiter;private final StoreProvisioningService provisioning;private final AdminSignupService signup;
    AdminController(AdminUserRepository admins,MembershipRepository memberships,StoreRepository stores,StoreAccessService access,PrizeRepository prizes,GameConfigService gameConfig,QrRepository qrs,StorePosterRepository posterRepository,StorePosterService posters,GameRepository games,CouponRepository coupons,PasswordEncoder encoder,JwtService jwt,SecureRandom random,Clock clock,PhoneService personalData,LoginAttemptLimiter loginLimiter,StoreProvisioningService provisioning,AdminSignupService signup){this.admins=admins;this.memberships=memberships;this.stores=stores;this.access=access;this.prizes=prizes;this.gameConfig=gameConfig;this.qrs=qrs;this.posterRepository=posterRepository;this.posters=posters;this.games=games;this.coupons=coupons;this.encoder=encoder;this.jwt=jwt;this.random=random;this.clock=clock;this.personalData=personalData;this.loginLimiter=loginLimiter;this.provisioning=provisioning;this.signup=signup;}
    record Login(@NotBlank @Size(max=255) String email,@NotBlank @Size(max=128) String password){}
    record SignUp(@NotBlank @Size(max=128) String password,@NotBlank @Size(max=128) String passwordConfirm,@NotBlank @Size(max=255) String email,@NotBlank @Size(max=50) String ownerName,@NotBlank @Size(max=20) String phone,@NotBlank @Size(max=100) String storeName,@NotBlank @Size(max=20) String businessNumber){} record StoreCreate(@NotBlank @Size(max=100) String name,@NotBlank @Size(max=20) String businessNumber,@NotBlank @Size(max=20) String phone,@Size(max=255) String address,@Size(max=500) @Pattern(regexp="|https?://.*") String naverPlaceUrl){} record StoreUpdate(@NotBlank @Size(max=100) String name,@Size(max=30) String phone,@Size(max=255) String address,@Size(max=500) @Pattern(regexp="|https?://.*") String naverPlaceUrl){} record PrizeUpdate(@NotBlank @Size(max=100) String name,@Size(max=500) String description,@NotNull RedeemPolicy redeemPolicy,boolean active){}
    record OutcomeSetting(@NotNull YutResult yutResult,int weight,int prizeRank){} record GameConfigUpdate(@NotNull List<@Valid OutcomeSetting> outcomes){}
    @PostMapping("/auth/signup") ApiResponse<?> signUp(@Valid @RequestBody SignUp r,HttpServletRequest req){StoreProvisioningService.Provisioned p=signup.signUp(new AdminSignupService.Request(r.password,r.passwordConfirm,r.email,r.ownerName,r.phone,r.storeName,r.businessNumber),origin(req));return ApiResponse.ok(Map.of("storeId",p.store().id,"storeName",p.store().name,"staffPin",p.staffPin(),"storeToken",p.storeToken(),"posterReady",true));}
    @PostMapping("/auth/login") ApiResponse<?> login(@Valid @RequestBody Login r,HttpServletRequest req){String ip=clientIp(req),email=Inputs.lower(r.email);loginLimiter.attempt(ip);AdminUser u=admins.findByEmail(email).filter(a->encoder.matches(r.password,a.passwordHash)).orElseThrow(()->new AppException("AUTH_INVALID","이메일 또는 비밀번호가 올바르지 않습니다.",org.springframework.http.HttpStatus.UNAUTHORIZED));loginLimiter.succeeded(ip);return ApiResponse.ok(Map.of("accessToken",jwt.issue(u),"tokenType","Bearer"));}
    @GetMapping("/stores") ApiResponse<?> stores(Authentication a){return ApiResponse.ok(memberships.findByAdminId(adminId(a)).stream().map(m->Map.of("id",m.store.id,"name",m.store.name,"businessNumber",m.store.businessNumber==null?"":m.store.businessNumber,"status",m.store.status)).toList());}
    @PostMapping("/stores") @Transactional ApiResponse<?> createStore(@Valid @RequestBody StoreCreate r,Authentication auth,HttpServletRequest req){AdminUser admin=admins.findById(adminId(auth)).orElseThrow();String name=Inputs.required(r.name,"매장 상호명을 입력해 주세요."),phone=Inputs.phone(r.phone),business=Inputs.businessNumber(r.businessNumber);if(memberships.countByAdminId(admin.id)>=MAX_STORES_PER_ADMIN)throw new AppException("STORE_LIMIT_REACHED","한 계정이 관리할 수 있는 매장 수를 넘었습니다.");if(stores.existsByBusinessNumber(business))throw new AppException("DUPLICATE_BUSINESS_NUMBER","이미 등록된 사업자등록번호입니다.");StoreProvisioningService.Provisioned p=provisioning.provision(admin,name,phone,r.address,business,r.naverPlaceUrl,null,origin(req));return ApiResponse.ok(Map.of("id",p.store().id,"name",p.store().name,"staffPin",p.staffPin(),"storeToken",p.storeToken(),"posterReady",true));}
    @GetMapping("/stores/{id}") ApiResponse<?> store(@PathVariable Long id,Authentication a){member(a,id);return ApiResponse.ok(storeView(store(id)));}
    @PutMapping("/stores/{id}") @Transactional ApiResponse<?> updateStore(@PathVariable Long id,@Valid @RequestBody StoreUpdate r,Authentication a,HttpServletRequest req){member(a,id);Store s=store(id);s.name=r.name.trim();if(r.phone!=null)s.phone=r.phone.trim();if(r.address!=null)s.address=r.address;if(r.naverPlaceUrl!=null)s.naverPlaceUrl=r.naverPlaceUrl;s.updatedAt=clock.instant();qrs.findFirstByStoreIdAndStatus(id,QrStatus.ACTIVE).ifPresent(q->posters.save(s,q.publicToken,origin(req)));return ApiResponse.ok(storeView(s));}
    @GetMapping("/stores/{id}/prizes") ApiResponse<?> prizes(@PathVariable Long id,Authentication a){member(a,id);return ApiResponse.ok(prizes.findByStoreIdOrderByRank(id).stream().map(this::prizeView).toList());}
    @PutMapping("/stores/{id}/prizes/{rank}") @Transactional ApiResponse<?> prize(@PathVariable Long id,@PathVariable int rank,@Valid @RequestBody PrizeUpdate r,Authentication a){member(a,id);Prize p=prizes.findByStoreIdAndRank(id,rank).orElseThrow(()->new AppException("PRIZE_NOT_FOUND","상품을 찾을 수 없습니다."));p.name=r.name;p.description=r.description;p.redeemPolicy=r.redeemPolicy;p.active=r.active;p.updatedAt=clock.instant();return ApiResponse.ok(prizeView(p));}
    @GetMapping("/stores/{id}/game-config") ApiResponse<?> gameConfig(@PathVariable Long id,Authentication a){member(a,id);return ApiResponse.ok(gameConfigView(gameConfig.load(id)));}
    @PutMapping("/stores/{id}/game-config") ApiResponse<?> saveGameConfig(@PathVariable Long id,@Valid @RequestBody GameConfigUpdate r,Authentication a){member(a,id);List<GameConfigService.Setting> settings=r.outcomes()==null?List.of():r.outcomes().stream().map(o->new GameConfigService.Setting(o.yutResult(),o.weight(),o.prizeRank())).toList();return ApiResponse.ok(gameConfigView(gameConfig.save(store(id),settings)));}
    @GetMapping("/stores/{id}/qr-codes") ApiResponse<?> qrs(@PathVariable Long id,Authentication a){member(a,id);return ApiResponse.ok(qrs.findByStoreIdOrderByCreatedAtDesc(id).stream().map(q->Map.of("token",q.publicToken,"status",q.status,"createdAt",q.createdAt)).toList());}
    @PostMapping("/stores/{id}/qr-codes/regenerate") @Transactional ApiResponse<?> regenerateQr(@PathVariable Long id,Authentication a,HttpServletRequest req){member(a,id);Store s=stores.findForUpdate(id).orElseThrow(()->new AppException("STORE_NOT_FOUND","매장을 찾을 수 없습니다."));qrs.findFirstByStoreIdAndStatus(id,QrStatus.ACTIVE).ifPresent(q->{q.status=QrStatus.REVOKED;q.revokedAt=clock.instant();});StoreQrCode q=new StoreQrCode();q.store=s;q.publicToken=Tokens.random();q.status=QrStatus.ACTIVE;q.createdAt=clock.instant();qrs.save(q);posters.save(s,q.publicToken,origin(req));return ApiResponse.ok(Map.of("token",q.publicToken,"posterReady",true));}
    @GetMapping(value="/stores/{id}/poster",produces=MediaType.IMAGE_PNG_VALUE) @Transactional ResponseEntity<byte[]> poster(@PathVariable Long id,Authentication a,HttpServletRequest req){member(a,id);Store s=store(id);StorePoster poster=posterRepository.findByStoreId(id).orElseGet(()->{StoreQrCode q=qrs.findFirstByStoreIdAndStatus(id,QrStatus.ACTIVE).orElseThrow(()->new AppException("QR_TOKEN_INVALID","활성 QR이 없습니다."));return posters.save(s,q.publicToken,origin(req));});String filename=s.name.replaceAll("[\\r\\n\\\\/:*?\"<>|]","_")+"_A6_QR.png";return ResponseEntity.ok().cacheControl(CacheControl.noStore()).header("X-Poster-Public-Origin",poster.publicOrigin).header(HttpHeaders.CONTENT_DISPOSITION,ContentDisposition.attachment().filename(filename,StandardCharsets.UTF_8).build().toString()).body(posters.bytes(poster));}
    @PostMapping("/stores/{id}/poster/regenerate") @Transactional ApiResponse<?> regeneratePoster(@PathVariable Long id,Authentication a,HttpServletRequest req){member(a,id);Store s=store(id);StoreQrCode q=qrs.findFirstByStoreIdAndStatus(id,QrStatus.ACTIVE).orElseThrow(()->new AppException("QR_TOKEN_INVALID","활성 QR이 없습니다."));StorePoster poster=posters.save(s,q.publicToken,origin(req));return ApiResponse.ok(Map.of("updatedAt",poster.updatedAt,"publicOrigin",poster.publicOrigin));}
    @PostMapping("/stores/{id}/staff-pin/regenerate") @Transactional ApiResponse<?> regeneratePin(@PathVariable Long id,Authentication a){member(a,id);String pin=Integer.toString(100000+random.nextInt(900000));Store s=store(id);s.staffPinHash=encoder.encode(pin);s.updatedAt=clock.instant();return ApiResponse.ok(Map.of("pin",pin));}
    @GetMapping("/stores/{id}/game-plays") ApiResponse<?> games(@PathVariable Long id,Authentication a){member(a,id);return ApiResponse.ok(games.findByStoreIdOrderByPlayedAtDesc(id).stream().map(g->Map.of("playId",g.publicId,"customerName",personalData.decrypt(g.customerNameEncrypted),"phoneLast4",g.phoneLast4,"result",g.yutResult,"prizeRank",g.prizeRank,"status",g.status,"playedAt",g.playedAt)).toList());}
    @GetMapping("/stores/{id}/coupons") ApiResponse<?> coupons(@PathVariable Long id,Authentication a){member(a,id);return ApiResponse.ok(coupons.findByStoreIdOrderByIssuedAtDesc(id).stream().map(c->Map.of("token",c.couponToken,"prizeName",c.prizeNameSnapshot,"status",c.status,"issuedAt",c.issuedAt,"expiresAt",c.expiresAt)).toList());}
    @GetMapping("/stores/{id}/analytics/summary") ApiResponse<?> analytics(@PathVariable Long id,Authentication a){member(a,id);Map<String,Long> results=new LinkedHashMap<>();for(YutResult result:YutResult.values())results.put(result.name(),games.countByStoreIdAndYutResult(id,result));return ApiResponse.ok(Map.of("todayPlays",games.countByStoreIdAndPlayedDate(id,java.time.LocalDate.now(clock)),"totalPlays",games.countByStoreId(id),"issuedCoupons",coupons.countByStoreIdAndStatus(id,CouponStatus.ISSUED),"redeemedCoupons",coupons.countByStoreIdAndStatus(id,CouponStatus.REDEEMED),"results",results));}
    private void member(Authentication a,Long id){access.member(adminId(a),id);} private Long adminId(Authentication a){return (Long)a.getPrincipal();} private Store store(Long id){return stores.findById(id).orElseThrow(()->new AppException("STORE_NOT_FOUND","매장을 찾을 수 없습니다."));}
    private Map<String,Object> gameConfigView(List<StoreOutcome> config){return Map.of("rankCount",GameConfigService.rankCount(config),"outcomes",config.stream().map(o->Map.of("yutResult",o.yutResult,"weight",o.weight,"prizeRank",o.prizeRank,"odds",GameConfigService.odds(config,x->x.yutResult==o.yutResult))).toList());}
    private Map<String,Object> prizeView(Prize p){return Map.of("rank",p.rank,"name",p.name,"description",p.description==null?"":p.description,"redeemPolicy",p.redeemPolicy,"active",p.active);}
    private Map<String,Object> storeView(Store s){return Map.of("id",s.id,"name",s.name,"phone",s.phone,"address",s.address==null?"":s.address,"naverPlaceUrl",s.naverPlaceUrl==null?"":s.naverPlaceUrl,"status",s.status);}
    private String clientIp(HttpServletRequest r){String proxied=r.getHeader("X-Real-IP");return proxied==null||proxied.isBlank()?r.getRemoteAddr():proxied;}
    private String origin(HttpServletRequest ignored){return ServletUriComponentsBuilder.fromCurrentContextPath().build().toUriString();}
}
